name: CI

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    runs-on: demao
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npx playwright install chromium --with-deps
